name: valdoria-dice
version: '1.0-SNAPSHOT'
main: com.valdoria.valdoriaDice.ValdoriaDice
api-version: '1.21'
commands:
  #player scope
  rolla:
    description: Rolls the dice of attack(1-12).
    usage: /rolla
    permission: dice.use
  rolld:
    description: Rolls the dice of defence(1-12).
    usage: /rolld
    permission: dice.use
  rollr:
    description: Rolls the dice of resist(1-12).
    usage: /rollr
    permission: dice.use

  rollam:
    description: Rolls the dice of magic attack(1-12).
    usage: /rollam
    permission: dice.use
  rolldm:
    description: Rolls the dice of magic defence(1-12).
    usage: /rolldm
    permission: dice.use
  rollrm:
    description: Rolls the dice of magic resist(1-12).
    usage: /rollrm
    permission: dice.use
  #admin scope
  rolladd:
    description: Admin command for adding some value to the rolling result of another player.
    usage: /rolladd [dice] [amount] [player]
    permission: dice.admin
  rollremove:
    description: Admin command for substracting some value from the rolling result of another player.
    usage: /rollremove [dice] [amount] [player]
    permission: dice.admin